### PR TITLE
Add shipping details parsing to Address

### PR DESCRIPTION
**Pull request by eloyesp**
Parse missing details on classes.

### CODE REVIEW

**Comment by sshaw** [comment]
Hi, thanks for the contribution. Is this ready for review? I see it's a draft so not sure.

**Comment by eloyesp** [comment]
My original intention was to add multiple missing fields with a single PR, but I cannot continue it right now, so you can review it as it is.

**Comment by sshaw** [comment]
@eloyesp!

Added this via [010bec6](https://github.com/ScreenStaring/recharge-api/commit/010bec6e547f97799ce30ae0906b6503f1ff8686) **but** didn't add `original_shipping_lines` as I did not see it in [the recharge docs](https://developer.rechargepayments.com/2021-11/). `original_shipping_lines` for address does seem off but, if it's not, let me know!

**Comment by sshaw** [comment]
Actually I see the problem: they're for different versions. Added `original_shipping_lines` in [9c841ce](https://github.com/ScreenStaring/recharge-api/commit/9c841ce147996a8304588b387daf17022f2efc77). Thanks!

**Pull request closed without merging**
